// src/app/lineas/lineas.component.ts
import { Component, OnInit } from '@angular/core';
import { ApiService } from '../api.service';
import { ApiLinea, ApiError, ApiNucleo } from '../interfaces/api-responses';

@Component({
  selector: 'app-lineas',
  templateUrl: './lineas.component.html',
  styleUrls: ['./lineas.component.scss']
})

export class LineasComponent implements OnInit {
  private lineas: ApiLinea[];
  private nucleos: ApiNucleo[];
  public filteredLineas: ApiLinea[];

  constructor(private api: ApiService) {}

  getNucleosNames(nucleos: string[]) {
    if(!nucleos) { return; }

    let nucleosNames: string[] = [];

    nucleos.forEach(nucleo => {
      const val = this.nucleos.find(n => n._id === nucleo);
      nucleosNames.push(val.name);
    })

    return nucleosNames;
  }

  updateLineas(search: HTMLInputElement) {
    const value = search.value.trim().toUpperCase();

    // Si la caja de búsqueda está vacía, mostrar todas las líneas
    if (!value || value === '') {
      this.filteredLineas = this.lineas;
      return;
    }

    const filtered = [];

    // Buscar coincidencias en destinos
    this.lineas.forEach(linea => {
      if (linea.nucleosInfo.some(n => n.name.includes(value))) {
        filtered.push(linea);
      }
    });

    // Buscar coincidencias en paradas
    const restantes = this.lineas.filter(l => !filtered.includes(l));
    restantes.forEach(linea => {
      if (linea.paradasInfo.some(p => p.name.includes(value))) {
        filtered.push(linea);
      }
    })

    this.filteredLineas = filtered;
  }

  ngOnInit() {
    this.api.fetchApi('http://localhost:3000/api/nucleos')
      .subscribe({
        next: (res: ApiNucleo[] | ApiError) => {
          if (this.api.hasError(res)) {
            console.error(res.error);
            return;
          }

          this.nucleos = res;
          console.log(this.nucleos);

          this.api.fetchApi('http://localhost:3000/api/lineas')
          .subscribe({
            next: (res: ApiLinea[] | ApiError) => {
              if (this.api.hasError(res)) {
                console.error(res.error);
                return;
              }
      
              this.lineas = res;
              this.filteredLineas = this.lineas;
              console.log(this.lineas);
            },
      
            error: (error) => {
              console.error(error);
            }
          });
        },

        error: (error) => {
          console.error(error);
        }
      });
  }
}

<h2>Líneas</h2>
<div>
    <input class="input full-width lineas-search" 
    type="search" 
    name="search" 
    placeholder="Buscar..."
    (input)="updateLineas($event.target)">
</div>
<app-linea-card 
    *ngFor="let linea of filteredLineas" 
    [linea]="linea"
    [nucleos]="getNucleosNames(linea.nucleosIda)">
</app-linea-card>

// src/views/Lineas.vue
<template>
  <div v-if="!loading" class="linea">
    <h1>Líneas</h1>
    <div>
      <ui-input
        v-model:value="searchQuery"
        :type="'search'"
        :name="'search'"
        :placeholder="'Buscar...'"
      />
    </div>
    <lineas-item
      v-for="linea of filteredLineas"
      :key="linea._id"
      :linea="linea"
      :nucleos="getNucleosNames(linea.nucleosIda)"
    />
  </div>
</template>

<script lang="ts">
import {
  computed, defineComponent, onMounted, ref,
} from 'vue';
import { useStore } from 'vuex';
import UiInput from '@/components/ui/UiInput.vue';
import LineasItem from '@/components/LineasItem.vue';
import ApiLineas from '@/lib/ApiLineas';
import ApiNucleos from '@/lib/ApiNucleos';
import { ApiLinea, ApiNucleo } from '@/interfaces/apiResponses';

export default defineComponent({
  name: 'Lineas',
  components: {
    UiInput,
    LineasItem,
  },

  setup() {
    const lineas = ref<ApiLinea[]>([]);
    const nucleos = ref<ApiNucleo[]>([]);
    const loading = ref(true);
    const searchQuery = ref('');
    const apiLineas = ApiLineas;
    const apiNucleos = ApiNucleos;
    const store = useStore();

    const urlBase = computed(() => store.state.urlBase);

    const filteredLineas = computed(() => {
      const value = searchQuery.value.trim().toUpperCase();
      if (value === '') return lineas.value;

      const filtered: ApiLinea[] = [];

      // Buscar coincidencias en destinos
      lineas.value.forEach(linea => {
        if (!linea.nucleosInfo) return;
        if (linea.nucleosInfo.some(n => n.name.includes(value))) {
          filtered.push(linea);
        }
      });

      // Buscar coincidencias en paradas
      const restantes = lineas.value.filter(l => !filtered.includes(l));
      restantes.forEach(linea => {
        if (!linea.paradasInfo) return;
        if (linea.paradasInfo.some(p => p.name.includes(value))) {
          filtered.push(linea);
        }
      });

      return filtered;
    });

    const getNucleosNames = (nucleosIds: string[]): string[] => {
      if (!nucleosIds) { return []; }
      const nucleosNames: string[] = [];

      nucleosIds.forEach(nucleo => {
        const val = nucleos.value.find(n => n._id === nucleo);

        if (!val) return;
        nucleosNames.push(val.name);
      });

      return nucleosNames;
    };

    onMounted(async () => {
      try {
        const nucleosResponse = await apiNucleos.getNucleos();
        nucleos.value = nucleosResponse;

        const lineasResponse = await apiLineas.getLineas();
        lineas.value = lineasResponse;
        loading.value = false;
      } catch (error) {
        console.log(error);
      }
    });

    return {
      urlBase,
      lineas,
      nucleos,
      loading,
      searchQuery,
      filteredLineas,
      getNucleosNames,
    };
  },
});
</script>
